# 数据源配置
spring:
  application:
    name: health-gzss-dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.20.105.181:1521/orcl
    username: cdc_gzss
    password: cdc_gzss

  data:
    redis:
      host: redis.shdata.me
      password: shdata9001
      port: 9001

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://172.20.107.35:7101/eureka

# 日志文件
logging:
  file:
    path: ./HC_logs/gzss/

zacian: #判断是否使用feign调用zacian，默认调用
  name: zacian2